const products = [
  {
    _id: '1',
    name: 'Apple Watch',
    image: '/images/apple-watch.jpeg',
    description: 'توضیحات محصول',
    price: 799,
    status: 12,
  },
  {
    _id: '2',
    name: 'Elegant-Watch',
    image: '/images/watch.jpg',
    description: 'توضیحات محصول',
    price: 1399,
    status: 5,
  },
  {
    _id: '3',
    name: 'Scooter Electric',
    image: '/images/scooter-1.jpg',
    description: 'توضیحات محصول',
    price: 1599,
    status: 'نامحدود',
  },
  {
    _id: '4',
    name: 'iPhone SE',
    image: '/images/iphone-se.jpg',
    description: 'توضیحات محصول',
    price: 2399,
    status: 3,
  },
  {
    _id: '5',
    name: 'MacBook 2',
    image: '/images/macbook2.jpg',
    description: 'توضیحات محصول',
    price: 4999,
    status: 'ناموجود',
  },
  {
    _id: '6',
    name: 'Logitech MX Master',
    image: '/images/mouse.jpg',
    description: 'توضیحات محصول',
    price: 79,
    status: 20,
  },
  {
    _id: '7',
    name: 'AirPods',
    image: '/images/airpods.jpg',
    description: 'توضیحات محصول',
    price: 119,
    status: 4,
  },
  {
    _id: '8',
    name: 'MacBook Pro',
    image: '/images/mac-book.jpeg',
    description: 'توضیحات محصول',
    price: 4899,
    status: 'ناموجود',
  },
  {
    _id: '9',
    name: 'Life Style',
    image: '/images/accessory.jpg',
    description: 'توضیحات محصول',
    price: 899,
    status: 2,
  },
  {
    _id: '10',
    name: 'Girls Scooter',
    image: '/images/scooter2.jpg',
    description: 'توضیحات محصول',
    price: 1299,
    status: 14,
  },
  {
    _id: '11',
    name: 'Orange-Radio',
    image: '/images/radio.jpg',
    description: 'توضیحات محصول',
    price: 419,
    status: 5,
  },
  {
    _id: '12',
    name: 'SunGlasses',
    image: '/images/glasses.jpg',
    description: 'توضیحات محصول',
    price: 59,
    status: 1,
  },
]

export default products
